version: '3.8'
services:
  queue:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data
  tgclient:
    image: tgclient
    build:
      context: .
      dockerfile: tgclient.Dockerfile
    restart: always
    ports:
      - '8001:8001'
    environment:
      - TG_APP_ID
      - TG_APP_HASH
      - APP_SECRET
    depends_on:
      - queue
  tdserver:
    image: tdserver
    build: 
      context: .
      dockerfile: tdserver.Dockerfile
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - queue
volumes:
  cache:
    driver: local